### ISSUE TITLE
Getting panic on env.parse

### ISSUE THREAD

**Issue by nwalke** [caarlos0/env#58]
Here's the error I'm seeing:
```
panic: reflect: reflect.Value.SetString using value obtained using unexported field

goroutine 1 [running]:
reflect.flag.mustBeAssignable(0x1b8)
	/usr/local/Cellar/go/1.11/libexec/src/reflect/value.go:231 +0x1ee
reflect.Value.SetString(0x1236e80, 0xc00009e1c0, 0x1b8, 0x12375cd, 0x4)
	/usr/local/Cellar/go/1.11/libexec/src/reflect/value.go:1551 +0x2b
github.com/caarlos0/env.set(0x1236e80, 0xc00009e1c0, 0x1b8, 0x1237592, 0x12, 0x120e897, 0x4, 0x12d95e0, 0x1236e80, 0x12375a6, ...)
	/Users/nick/go/src/github.com/caarlos0/env/env.go:161 +0xb55
github.com/caarlos0/env.doParse(0x126fba0, 0xc00009e1c0, 0x199, 0xc0000d3be0, 0xc00009e1c0, 0x199)
	/Users/nick/go/src/github.com/caarlos0/env/env.go:92 +0x2ce
github.com/caarlos0/env.Parse(0x122ba20, 0xc00009e1c0, 0x3, 0xc00009c3f0)
	/Users/nick/go/src/github.com/caarlos0/env/env.go:53 +0x1a1
main.main()
	/Users/nick/projects/tautulli-exporter/main.go:70 +0x5f
exit status 2
```

Here's my config struct:
```
type config struct {
	tautulliHttpMethod string `env:"TAUTULLI_HTTP_METHOD" envDefault:"http"`
	tautulliHost       string `env:"TAUTULLI_ADDRESS" envDefault:"127.0.0.1:8181"`
	tautulliApiKey     string `env:"TAUTULLI_API_KEY"`
	servePort          string `env:"SERVE_PORT" envDefault:"8282"`
}
```

Line 70 in my `main.go` is just a copy paste from the example in the README, so not sure what I'm doing wrong here...

I've removed some extraneous comments and posted the whole file here: https://gist.github.com/nwalke/db4825f01049afd95793f0fc15fb666d

Line 70 from the stack above is line 25 in that gist.

Any help would be much appreciated!

**Comment by nwalke** [comment]
The struct fields have to be capitalized...  son of a gun.
